There is no need to save default NoticeSetting instances. Under some rare circumstances (impatient users firing off multiple requests in parallel) the .save() here could also result in:
IntegrityError: duplicate key value violates unique constraint "notification_noticesetting_user_id_key"